import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import numpy as np
import io
from scipy.signal import find_peaks
import plotly.graph_objects as go

# ---------------------------------------------------------
# 1. ページ設定
# ---------------------------------------------------------
st.set_page_config(page_title="XRD Plotter Pro", layout="wide")
st.title("🔬 XRD Multi-Plotter Pro")

# ---------------------------------------------------------
# 2. 関数：データ読み込み & スクリプト生成
# ---------------------------------------------------------
def load_xrd_data_full(uploaded_file):
    try:
        content = ""
        for enc in ['utf-8', 'cp932', 'shift_jis']:
            try:
                uploaded_file.seek(0)
                content = uploaded_file.read().decode(enc)
                break
            except: continue
        if not content: return None
        lines = content.splitlines()
        data_start_idx = 0
        for i, line in enumerate(lines):
            parts = line.replace('\t', ',').replace(' ', ',').split(',')
            parts = [p for p in parts if p.strip()]
            if len(parts) >= 2:
                try:
                    float(parts[0].strip()); float(parts[1].strip())
                    data_start_idx = i
                    break
                except ValueError: continue
        uploaded_file.seek(0)
        df = pd.read_csv(uploaded_file, skiprows=data_start_idx, header=None, sep=None, engine='python')
        df = df.apply(pd.to_numeric, errors='coerce').dropna(axis=0, how='any')
        if df.empty: return None
        df.columns = [f"Column {i}" for i in range(df.shape[1])]
        return df
    except Exception as e:
        st.error(f"Error parsing {uploaded_file.name}: {e}")
        return None

def generate_gnuplot_script(selected_data, styles, x_range, y_offset, x_col, y_col):
    """gnuplot用スクリプトを生成する"""
    script = f"""# Gnuplot script generated by XRD Plotter Pro
set terminal pngcairo enhanced font 'Arial,12' size 800,600
set output 'xrd_plot.png'
set xlabel "2-theta (deg.)"
set ylabel "Intensity (a.u.)"
set xrange [{x_range[0]}:{x_range[1]}]
set key linestyle -1
"""
    plot_cmds = []
    for i, d in enumerate(selected_data):
        s = styles[d['name']]
        # gnuplot形式で各ファイルをプロットするコマンド (ファイル名は仮でdata.csvとする)
        # 実際にはすべてのデータを結合したひとつのCSVを参照する形に
        offset = i * y_offset
        color = s['color']
        plot_cmds.append(f"'processed_data.csv' u 1:({i+2} * {s['scale']} + {offset}) w l lc rgb '{color}' lw {s['lw']} title '{d['name']}'")
    
    script += "plot " + ", \\\n     ".join(plot_cmds)
    return script

# ---------------------------------------------------------
# 3. メインロジック
# ---------------------------------------------------------
st.sidebar.header("1. Data Import")
uploaded_files = st.sidebar.file_uploader("ファイルをアップロード", type=['csv', 'txt', '2ta', 'dat', 'xy'], accept_multiple_files=True)

all_data = []
if uploaded_files:
    for f in uploaded_files:
        df = load_xrd_data_full(f)
        if df is not None:
            all_data.append({"name": f.name, "df": df})

selected_data = []
individual_styles = {}

if all_data:
    st.sidebar.header("2. Style & Scaling")
    max_cols = max([d["df"].shape[1] for d in all_data])
    col_options = [f"Column {i}" for i in range(max_cols)]
    x_col = st.sidebar.selectbox("X軸 (2θ)", col_options, index=0)
    y_col = st.sidebar.selectbox("Y軸 (Intensity)", col_options, index=1 if max_cols > 1 else 0)

    for i, d in enumerate(all_data):
        if st.sidebar.checkbox(d["name"], value=True, key=f"c_{d['name']}"):
            with st.sidebar.expander(f"🎨 {d['name']}"):
                scale = st.number_input("倍率", value=1.0, step=0.1, key=f"s_{i}")
                color = st.color_picker("色", mcolors.to_hex(plt.cm.tab10(i % 10)), key=f"cp_{i}")
                lw = st.slider("太さ", 0.5, 5.0, 1.5, key=f"l_{i}")
                individual_styles[d['name']] = {"scale": scale, "color": color, "lw": lw, "ls": "-"}
                selected_data.append(d)

if selected_data:
    # 共通設定
    st.sidebar.header("3. Global View")
    all_x = pd.concat([d["df"][x_col] for d in selected_data])
    x_range = st.sidebar.slider("表示範囲 (2θ)", float(all_x.min()), float(all_x.max()), (float(all_x.min()), float(all_x.max())))
    y_offset = st.sidebar.number_input("積み上げオフセット", value=0.0, step=100.0)
    dpi_val = st.sidebar.select_slider("出力解像度 (DPI)", options=[72, 150, 300, 600], value=300)

    # --- グラフ表示 ---
    fig, ax = plt.subplots(figsize=(10, 6))
    export_df = pd.DataFrame() # 出力用データ
    
    for i, d in enumerate(selected_data):
        style = individual_styles[d['name']]
        x = d["df"][x_col]
        y_raw = d["df"][y_col]
        y_scaled = y_raw * style["scale"]
        y_disp = y_scaled + (i * y_offset)
        
        ax.plot(x, y_disp, label=f"{d['name']} (x{style['scale']})", 
                color=style["color"], linewidth=style["lw"])
        
        # 出力用CSVの作成（X軸を揃えるための簡易処理）
        if i == 0: export_df['2theta'] = x
        export_df[d['name']] = y_raw

    ax.set_xlim(x_range)
    ax.set_xlabel("2-theta (deg.)")
    ax.set_ylabel("Intensity (a.u.)")
    ax.legend()
    st.pyplot(fig)

    # --- 保存・エクスポート機能 ---
    st.divider()
    st.subheader("💾 Export Results")
    col1, col2, col3 = st.columns(3)

    with col1:
        # 1. 画像保存 (DPI指定可能)
        buf = io.BytesIO()
        fig.savefig(buf, format="png", dpi=dpi_val, bbox_inches='tight')
        st.download_button("🖼 画像を保存 (PNG)", buf.getvalue(), "xrd_plot.png", "image/png")
        st.caption(f"現在の設定: {dpi_val} DPI")

    with col2:
        # 2. gnuplot用スクリプト保存
        gp_script = generate_gnuplot_script(selected_data, individual_styles, x_range, y_offset, x_col, y_col)
        st.download_button("📜 gnuplotスクリプト保存", gp_script, "plot_script.gp", "text/plain")
        st.caption("設定内容を反映した.gpファイル")

    with col3:
        # 3. 解析用データ (CSV) 保存
        csv_data = export_df.to_csv(index=False).encode('utf-8')
        st.download_button("📊 データを保存 (CSV)", csv_data, "processed_data.csv", "text/csv")
        st.caption("gnuplotで読み込むためのCSV")

    st.info("💡 **gnuplotの使い方**: ダウンロードした CSV と .gp を同じフォルダに置き、`gnuplot plot_script.gp` を実行してください。")

else:
    st.info("データをアップロードして、表示するファイルにチェックを入れてください。")