import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import numpy as np
import io
from scipy.signal import find_peaks
import plotly.graph_objects as go

# ---------------------------------------------------------
# 1. ページ設定
# ---------------------------------------------------------
st.set_page_config(page_title="XRD Plotter Pro", layout="wide")
st.title("🔬 XRD Multi-Plotter Pro (Full Integrated)")

# ---------------------------------------------------------
# 2. 関数：データ読み込み & エクスポート用処理
# ---------------------------------------------------------
def load_xrd_data_full(uploaded_file):
    try:
        content = ""
        for enc in ['utf-8', 'cp932', 'shift_jis']:
            try:
                uploaded_file.seek(0)
                content = uploaded_file.read().decode(enc)
                break
            except: continue
        if not content: return None
        lines = content.splitlines()
        data_start_idx = 0
        for i, line in enumerate(lines):
            parts = line.replace('\t', ',').replace(' ', ',').split(',')
            parts = [p for p in parts if p.strip()]
            if len(parts) >= 2:
                try:
                    float(parts[0].strip()); float(parts[1].strip())
                    data_start_idx = i
                    break
                except ValueError: continue
        uploaded_file.seek(0)
        df = pd.read_csv(uploaded_file, skiprows=data_start_idx, header=None, sep=None, engine='python')
        df = df.apply(pd.to_numeric, errors='coerce').dropna(axis=0, how='any')
        if df.empty: return None
        df.columns = [f"Column {i}" for i in range(df.shape[1])]
        return df
    except Exception as e:
        st.error(f"Error parsing {uploaded_file.name}: {e}")
        return None

def generate_gnuplot_script(selected_data, styles, x_range, y_offset):
    script = f"""# Gnuplot script generated by XRD Plotter Pro
set terminal pngcairo enhanced font 'Arial,12' size 800,600
set output 'xrd_plot.png'
set xlabel "2-theta (deg.)"
set ylabel "Intensity (a.u.)"
set xrange [{x_range[0]}:{x_range[1]}]
set key linestyle -1
"""
    plot_cmds = []
    for i, d in enumerate(selected_data):
        s = styles[d['name']]
        offset = i * y_offset
        plot_cmds.append(f"'processed_data.csv' u 1:(${i+2} * {s['scale']} + {offset}) w l lc rgb '{s['color']}' lw {s['lw']} title '{d['name']}'")
    script += "plot " + ", \\\n     ".join(plot_cmds)
    return script

# ---------------------------------------------------------
# 3. サイドバー: データ・スタイル設定
# ---------------------------------------------------------
st.sidebar.header("1. Data Import")
uploaded_files = st.sidebar.file_uploader("ファイルを読み込む", type=['csv', 'txt', 'dat', 'xy'], accept_multiple_files=True)

all_data = []
if uploaded_files:
    for f in uploaded_files:
        df = load_xrd_data_full(f)
        if df is not None:
            all_data.append({"name": f.name, "df": df})

selected_data = []
individual_styles = {}

if all_data:
    st.sidebar.header("2. Style & Scaling")
    max_cols = max([d["df"].shape[1] for d in all_data])
    x_col = st.sidebar.selectbox("X軸 (2θ)", [f"Column {i}" for i in range(max_cols)], index=0)
    y_col = st.sidebar.selectbox("Y軸 (Intensity)", [f"Column {i}" for i in range(max_cols)], index=1 if max_cols > 1 else 0)

    for i, d in enumerate(all_data):
        if st.sidebar.checkbox(d["name"], value=True, key=f"cb_{i}"):
            with st.sidebar.expander(f"🎨 {d['name']}"):
                sc = st.number_input("強度倍率", value=1.0, step=0.1, key=f"sc_{i}")
                cp = st.color_picker("色", mcolors.to_hex(plt.cm.tab10(i % 10)), key=f"cp_{i}")
                lw = st.slider("線の太さ", 0.5, 5.0, 1.5, key=f"lw_{i}")
                individual_styles[d['name']] = {"scale": sc, "color": cp, "lw": lw}
                selected_data.append(d)

# ---------------------------------------------------------
# 4. メイン表示 (Plotlyによるインタラクティブ解析)
# ---------------------------------------------------------
if selected_data:
    # 共通設定
    st.sidebar.header("3. Global Settings")
    all_x = pd.concat([d["df"][x_col] for d in selected_data])
    x_range = st.sidebar.slider("表示範囲 (2θ)", float(all_x.min()), float(all_x.max()), (float(all_x.min()), float(all_x.max())))
    y_offset = st.sidebar.number_input("積み上げオフセット", value=0.0, step=100.0)
    
    use_peak_finder = st.sidebar.checkbox("ピーク検出を表示", value=False)
    peak_prom = st.sidebar.number_input("ピーク感度", value=50.0, step=10.0) if use_peak_finder else 0

    # --- インタラクティブグラフ (Plotly) ---
    st.subheader("🔍 Interactive Analysis (Hover to read values)")
    fig_plotly = go.Figure()
    peak_results = []
    export_df = pd.DataFrame()

    for i, d in enumerate(selected_data):
        style = individual_styles[d['name']]
        x = d["df"][x_col]
        y_scaled = d["df"][y_col] * style["scale"]
        y_disp = y_scaled + (i * y_offset)
        
        # Plotlyプロット
        fig_plotly.add_trace(go.Scatter(
            x=x, y=y_disp, name=d["name"], mode='lines',
            line=dict(color=style["color"], width=style["lw"]),
            hovertemplate = f'2θ: %{{x:.3f}}<br>Int(Scaled): %{{y:.1f}}<br>File: {d["name"]}'
        ))

        # データ出力用
        if i == 0: export_df['2theta'] = x
        export_df[d['name']] = d["df"][y_col]

        # ピーク検出
        if use_peak_finder:
            peaks, _ = find_peaks(y_scaled, prominence=peak_prom)
            mask = (x.iloc[peaks] >= x_range[0]) & (x.iloc[peaks] <= x_range[1])
            fig_plotly.add_trace(go.Scatter(
                x=x.iloc[peaks][mask], y=y_disp.iloc[peaks][mask],
                mode='markers+text', text=[f"{v:.2f}" for v in x.iloc[peaks][mask]],
                textposition="top center", marker=dict(symbol='triangle-up', size=8), showlegend=False
            ))
            for p in peaks:
                peak_results.append({"File": d["name"], "2θ": x.iloc[p], "Intensity(Scaled)": y_scaled.iloc[p]})

    fig_plotly.update_layout(
        xaxis=dict(title="2-theta (deg.)", range=x_range),
        yaxis=dict(title="Intensity (a.u.)"),
        height=600, template="plotly_white", hovermode="x unified"
    )
    st.plotly_chart(fig_plotly, use_container_width=True)

    # ---------------------------------------------------------
    # 5. エクスポート機能
    # ---------------------------------------------------------
    st.divider()
    st.subheader("💾 Export & Save")
    c1, c2, c3 = st.columns(3)

    with c1:
        # 画像保存用にMatplotlibで描画
        fig_mpl, ax = plt.subplots(figsize=(10, 6))
        for i, d in enumerate(selected_data):
            style = individual_styles[d['name']]
            ax.plot(d["df"][x_col], (d["df"][y_col] * style["scale"]) + (i * y_offset),
                    color=style["color"], linewidth=style["lw"], label=d["name"])
        ax.set_xlim(x_range); ax.set_xlabel("2-theta (deg.)"); ax.set_ylabel("Intensity (a.u.)")
        ax.legend(prop={'size': 8})
        
        dpi_val = st.select_slider("保存DPI", [72, 150, 300, 600], value=300)
        buf = io.BytesIO()
        fig_mpl.savefig(buf, format="png", dpi=dpi_val, bbox_inches='tight')
        st.download_button("🖼 画像を保存 (PNG)", buf.getvalue(), "xrd_plot.png", "image/png")

    with c2:
        gp_script = generate_gnuplot_script(selected_data, individual_styles, x_range, y_offset)
        st.download_button("📜 gnuplotスクリプト保存", gp_script, "plot_script.gp", "text/plain")

    with c3:
        csv_data = export_df.to_csv(index=False).encode('utf-8')
        st.download_button("📊 データ(CSV)保存", csv_data, "processed_data.csv", "text/csv")

    if use_peak_finder and peak_results:
        with st.expander("📋 ピークリストを表示"):
            st.table(pd.DataFrame(peak_results))

else:
    st.info("サイドバーからデータをアップロードし、ファイルを選択してください。")